apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  labels:
    pv: nfs-pv
spec:
  capacity:
    storage: 10Gi # 指定pv的容量为10Gi
  accessModes:
    - ReadWriteMany  # pv能以readWriteMany模式mount到单个节点
  storageClassName: nfs
  nfs:
    path: /home/vagrant/nfsshare
    server: 192.168.42.40