apiVersion: v1
kind: Pod
metadata:
  name: test-pv-pvc
spec:
  containers:
  - image: ubuntu:latest
    name: base-ubuntu
    volumeMounts:
    - name: nsf
      mountPath: /data
    ports:
    - containerPort: 27017
      protocol: TCP
  volumes:
  - name: nsf
    persistentVolumeClaim:
      claimName: base-nfs-pvc
