apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: base-nfs-pvc
  labels:
    app: base-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs
  selector:
    matchLabels:
      pv: nfs-pv
