apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs
  labels:
    pv: nfs-pv
spec:
  capacity:
    storage: 10Gi # 指定pv的容量为10Gi
  accessModes:
    - ReadWriteMany  # pv能允许多个节点读写

  storageClassName: nfs
  nfs:
    path: /home/nfsshare
    server: 192.168.42.40